"""create initial schema

Revision ID: db0caa03a995
Revises:
Create Date: 2026-07-17 14:44:25.651517
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "db0caa03a995"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "partial",
                "failed",
                name="crawlstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("source_total", sa.Integer(), nullable=False),
        sa.Column("source_success", sa.Integer(), nullable=False),
        sa.Column("source_failed", sa.Integer(), nullable=False),
        sa.Column("discovered_count", sa.Integer(), nullable=False),
        sa.Column("new_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("unclassified_count", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "rss",
                "html_list",
                "github_release",
                "json_api",
                "custom",
                name="sourcetype",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("start_url", sa.String(length=2048), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "default_category",
            sa.Enum(
                "model_technology",
                "agent_product",
                "enterprise_case",
                "award_case",
                "solicitation",
                "policy_industry",
                "unclassified",
                name="category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("collector_name", sa.String(length=100), nullable=False),
        sa.Column("collector_config", sa.JSON(), nullable=False),
        sa.Column("discovery_status", sa.String(length=50), nullable=True),
        sa.Column("discovery_confidence", sa.Float(), nullable=True),
        sa.Column("requires_custom_collector", sa.Boolean(), nullable=False),
        sa.Column(
            "origin",
            sa.Enum(
                "preset",
                "user_added",
                "imported",
                name="sourceorigin",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("start_url"),
    )
    op.create_table(
        "intelligence_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("original_url", sa.String(length=2048), nullable=False),
        sa.Column("canonical_url", sa.String(length=2048), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "model_technology",
                "agent_product",
                "enterprise_case",
                "award_case",
                "solicitation",
                "policy_industry",
                "unclassified",
                name="category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("classification_score", sa.Float(), nullable=True),
        sa.Column("classification_reason", sa.Text(), nullable=True),
        sa.Column("automatic_category_provider", sa.String(length=100), nullable=True),
        sa.Column(
            "manual_category",
            sa.Enum(
                "model_technology",
                "agent_product",
                "enterprise_case",
                "award_case",
                "solicitation",
                "policy_industry",
                "unclassified",
                name="category",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_url"),
        sa.UniqueConstraint("source_id", "fingerprint", name="uq_item_source_fingerprint"),
    )
    op.create_index(
        op.f("ix_intelligence_items_source_id"), "intelligence_items", ["source_id"], unique=False
    )
    op.create_index(
        "ix_items_category_discovered",
        "intelligence_items",
        ["category", "discovered_at"],
        unique=False,
    )
    op.create_table(
        "item_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("crawl_run_id", sa.Integer(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("old_data", sa.JSON(), nullable=False),
        sa.Column("new_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["crawl_run_id"], ["crawl_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["item_id"], ["intelligence_items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_item_revisions_crawl_run_id"), "item_revisions", ["crawl_run_id"], unique=False
    )
    op.create_index(op.f("ix_item_revisions_item_id"), "item_revisions", ["item_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_revisions_item_id"), table_name="item_revisions")
    op.drop_index(op.f("ix_item_revisions_crawl_run_id"), table_name="item_revisions")
    op.drop_table("item_revisions")
    op.drop_index("ix_items_category_discovered", table_name="intelligence_items")
    op.drop_index(op.f("ix_intelligence_items_source_id"), table_name="intelligence_items")
    op.drop_table("intelligence_items")
    op.drop_table("sources")
    op.drop_table("crawl_runs")
    # ### end Alembic commands ###
